### ISSUE TITLE
Delete branch feature/#8-cli

### ISSUE THREAD

**Issue by JakeOShannessy** [Daolab/beaker-cli#21]
This was an attempt to implement the cli using opt-parse-generic. In the end we took a different route, and everything implemented by this @road21  and I implemented with optparse-applicative.

Is everyone ok if I delete this?

**Comment by Latrasis** [comment]
@JakeOShannessy: I believe we can go ahead and remove this for now.

**Comment by JakeOShannessy** [comment]
done
